/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio22;

import java.util.Scanner;

public class Main {

    public static void main(String[] args) {

        Scanner leitorScanner = new Scanner(System.in);

        String nomeProduto;
        float precoCusto;
        float precoVenda;
        float totalCusto = 0.0f;
        float totalVenda = 0.0f;
        int i = 0;
        
          
        

        for (; i < 3; i++) {
            System.out.println("Digite o nome do produto: ");
            nomeProduto = leitorScanner.nextLine();
            System.out.println("Digite o preço de custo do produto: ");
            precoCusto = leitorScanner.nextFloat();
            System.out.println("Digite o preço de venda do produto: ");
            precoVenda = leitorScanner.nextFloat();
            
            totalCusto = totalCusto + precoCusto;
            totalVenda = totalVenda + precoVenda; 
            
            if(precoCusto == precoVenda){
                System.out.println("Houve um empate entre o preço de custo e de venda");
            }else{
                if(precoCusto > precoVenda){
                    System.out.println("Prejuízo");
                }else{
                    System.out.println("Lucro");
                }
                
            }
            
            System.out.println(nomeProduto + ", preço custo = " 
                    + precoCusto + ", preço de venda = " + precoVenda);

        }
        
        System.out.println("A média de custo é de: " + (totalCusto / i) );
        System.out.println("A média de preço de venda é de: " + (totalVenda / i));


    }
}
